//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SignalRChat
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class OTRAndroidEntities : DbContext
    {
        public OTRAndroidEntities()
            : base("name=OTRAndroidEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ChatMessageDetail> ChatMessageDetails { get; set; }
        public virtual DbSet<ChatPrivateMessage> ChatPrivateMessages { get; set; }
        public virtual DbSet<ChatPrivateMessageDetail> ChatPrivateMessageDetails { get; set; }
        public virtual DbSet<ChatUserDetail> ChatUserDetails { get; set; }
    }
}
